{
 "title": "ScoutAM",
 "description": "ScoutAM dashboard modeled after the Library of Congress VSM visualizations.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance_pattern",
    "label": "ScoutAM Cluster",
    "query": "Cluster 1 : s[123]{1}.*, Cluster 2 : s8[123]{1}.*"
   },
   {
    "name": "leader",
    "label": "ScoutAM Leader",
    "query": {
     "query": "label_values(scoutam_leader{leader=\"True\"}, fqdn)"
    }
   },
   {
    "name": "network_pattern",
    "label": "Network Interface",
    "query": {
     "query": "label_values(node_network_info,device)"
    }
   },
   {
    "name": "mdraid_pattern",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_info,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduler Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (queue) (topk(1, scoutam_scheduler{queue=\"ARCHIVING\", instance=~\"$leader.*\"}))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "max by (queue) (topk(1, scoutam_scheduler{queue=\"STAGING\", instance=~\"$leader.*\"}))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "max by (queue) (topk(1, scoutam_scheduler{queue=\"SCHEDULER\", instance=~\"$leader.*\"}))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "ScoutFS Data Capacity",
   "type": "timeseries",
   "description": "Data capacity for ScoutFS filesystem.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (hostanme) (scoutam_fs_data_size_capacity{hostname=\"scheduler\", instance=~\"$leader.*\"})",
     "legendFormat": "Total capacity"
    },
    {
     "expr": "sum by (hostanme) (scoutam_fs_releasable_size{hostname=\"scheduler\", instance=~\"$leader.*\"})",
     "legendFormat": "Releasable"
    },
    {
     "expr": "sum by (hostanme) (scoutam_fs_highwatermark{hostname=\"scheduler\", instance=~\"$leader.*\"})",
     "legendFormat": "High watermark"
    },
    {
     "expr": "sum by (hostanme) (scoutam_fs_lowwatermark{hostname=\"scheduler\", instance=~\"$leader.*\"})",
     "legendFormat": "Low watermark"
    },
    {
     "expr": "sum by (hostanme) (scoutam_fs_data_size_capacity{hostname=\"scheduler\", instance=~\"$leader.*\"} - scoutam_fs_data_size_free{hostname=\"scheduler\", instance=~\"$leader.*\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Scheduler Overview",
   "type": "timeseries",
   "description": "Show the total number of files archiving and staging.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum (scoutam_sched_sections{type=\"archive\",instance=~\"$leader.*\"})",
     "legendFormat": "Total archive files"
    },
    {
     "expr": "sum (scoutam_sched_sections{type=\"stage\",instance=~\"$leader.*\"})",
     "legendFormat": "Total stage files"
    }
   ]
  },
  {
   "title": "ScoutFS Data Free",
   "type": "gauge",
   "description": "Free percentage of ScoutFS data",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scoutam_fs_data_size_free{hostname=\"scheduler\", instance=~\"$leader.*\"} / scoutam_fs_data_size_capacity{hostname=\"scheduler\", instance=~\"$leader.*\"}) * 100",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "ScoutFS Metadata Capacity",
   "type": "gauge",
   "description": "Free percentage of ScoutFS metadata",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scoutam_fs_metadata_size_free{hostname=\"scheduler\", instance=~\"$leader.*\"} / scoutam_fs_metadata_size_capacity{hostname=\"scheduler\", instance=~\"$leader.*\"}) * 100",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Current ScoutFS Leader",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (scoutam_leader{leader=\"True\",instance=~\"$instance_pattern\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Overall Tape Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain) (scoutam_catalog_full{pool != \"default\", domain !~ \"(s3|posix)\", instance=~\"$leader.*\"})",
     "legendFormat": "Full {{domain}}"
    },
    {
     "expr": "sum by (domain) (scoutam_catalog_error{pool != \"default\", domain !~ \"(s3|posix)\", instance=~\"$leader.*\"} + scoutam_catalog_needsattention{pool != \"default\", instance=~\"$leader.*\"})",
     "legendFormat": "Error/Attention {{domain}}"
    },
    {
     "expr": "sum by (domain) (scoutam_catalog_drain{pool != \"default\", domain !~ \"(s3|posix)\", instance=~\"$leader.*\"})",
     "legendFormat": "Recycle {{domain}}"
    }
   ]
  },
  {
   "title": "Cache Accounting",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scoutam_acct{type=\"cache\", name=\"unmatched\", instance=~\"$instance_pattern\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "scoutam_acct{type=\"cache\", name=\"noarchive\", instance=~\"$instance_pattern\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "scoutam_acct{type=\"cache\", name=\"damaged\", instance=~\"$instance_pattern\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Archive and Stage Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Archive Speed Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (command) (rate(scoutam_scsi_sg_cmd_data{command=\"write\", instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Speed Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (command) (rate(scoutam_scsi_sg_cmd_data{command=\"read\", instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archive Speed By Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(scoutam_scsi_sg_cmd_data{command=\"write\",instance=~\"$instance_pattern\", instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Stage Speed By Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(scoutam_scsi_sg_cmd_data{command=\"read\",instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archive Speed By Drive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (drive) (rate(scoutam_scsi_sg_cmd_data{command=\"write\", instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Speed By Drive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (drive) (rate(scoutam_scsi_sg_cmd_data{command=\"read\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scheduler Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Archive Files",
   "type": "timeseries",
   "description": "Archive file count by queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (queue) (scoutam_sched_sections{type=\"archive\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Stage Files",
   "type": "timeseries",
   "description": "Stage file count by queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (queue) (scoutam_sched_sections{type=\"stage\", instance=~\"$instance_pattern\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Top 10 Online Projects by Size",
   "type": "bargauge",
   "description": "Top 10 consumers of online data capacity.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (sum_over_time(scoutam_acct{type=\"project\", category=\"online\", metric=\"size\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Online Projects by File Count",
   "type": "bargauge",
   "description": "Top 10 consumers of online data by file count.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (sum_over_time(scoutam_acct{type=\"project\", category=\"online\", metric=\"files\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Archive Projects by Size",
   "type": "bargauge",
   "description": "Top 10 consumers of archive data capacity.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (sum_over_time(scoutam_acct{type=\"project\", category=\"total\", metric=\"size\"}[$__interval])) - sum by (name) (sum_over_time(scoutam_acct{type=\"project\", category=\"online\", metric=\"size\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Archive Projects by Files",
   "type": "bargauge",
   "description": "Top 10 consumers of archive files.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (sum_over_time(scoutam_acct{type=\"project\", category=\"total\", metric=\"files\"}[$__interval])) - sum by (name) (sum_over_time(scoutam_acct{type=\"project\", category=\"online\", metric=\"files\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percentage of CPU usage over 10 minute time frame",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance_pattern\"}[10m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Amount of active memory used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=~\"$instance_pattern\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "ScoutFS device throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{device=~\"$mdraid_pattern\",instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{device=~\"$mdraid_pattern\",instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk I/O Throughput",
   "type": "timeseries",
   "description": "ScoutFS device throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"$mdraid_pattern\",instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$mdraid_pattern\",instance=~\"$instance_pattern\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{instance=~\"$instance_pattern\", device != \"lo\", device=~\"$network_pattern\"}[$__rate_interval])*8) * -1",
     "legendFormat": "{{instance}} {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance_pattern\", device != \"lo\", device=~\"$network_pattern\"}[$__rate_interval]) * 8 ",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  }
 ]
}